### ISSUE TITLE
Reverse animation skipped

### ISSUE THREAD

**Issue by lucasmodesto** [kirillgerasimov/Shared-Element-View-Pager#1]
Sometimes, it's skipping the transition animation when going backwards, usually when swiping fast between the pages, do you have a clue why it happens or if there's a way to prevent it?

**Comment by kirillgerasimov** [comment]
Hello, 
This lib seems to be pretty buggy at the moment. I'm currently working on another project so I'm not sure if I can help but I'll take a look. 

Can you share a code where you creating transformer and creating transitions?
```SePageTransformer transformer = ...```

**Comment by lucasmodesto** [comment]
Hello, beside this problem it seems to work alright.

So I have 4 fragments on Viewpager adapter, view pager setup code:

        val sectionsPagerAdapter = SectionsPagerAdapter(this, fragments, supportFragmentManager)
        val transformer = DefaultSePageTransformer(this, fragments, viewPager)
        transformer.addTransition(R.id.ivProfile1, R.id.ivProfile2, true)
        transformer.addTransition(R.id.ivLogo1, R.id.ivLogo2, true)
        transformer.addTransition(R.id.ivLogo2, R.id.ivLogo3, true)
        transformer.addTransition(R.id.ivLogo3, R.id.ivLogo4, true)
        transformer.addTransition(R.id.rv2, R.id.rv3, true)

        viewPager?.setPageTransformer(false, transformer)
        viewPager?.addOnPageChangeListener(transformer)
        viewPager?.adapter = sectionsPagerAdapter`

Thanks for helping!

**Comment by lucasmodesto** [comment]
Hi, I made a test importing library classes into my project instead of adding gradle dependency and the problem is gone. I think it is something related with androidX version.
